#!/bin/bash
# aqi : Shows AQI (Air Quality Index) from http://aqicn.org
# Usage : aqi [city] => shows aqi of a city.
#       : aqi [xxx-gu] => shows aqi of xxx district in seoul.
#       : aqi -s    => shows all district in seoul.
#       : aqi -i    => shows some international cities
#       : aqi -c    => shows cities in south korea

cities="ansan anyang bucheon cheonan cheongju daegu daejeon gimhae goyang gwangju suwon incheon jeonju pohang seongnam seoul"
gus="dobong-gu dongdaemun-gu dongjak-gu gangnam-gu gangseo-gu geumcheon-gu guro-gu gwangjin-gu jongno-gu jung-gu mapo-gu nowon-gu seodaemun-gu seocho-gu songpa-gu yangcheon-gu yeongdeungpo-gu yongsan-gu gwanak-gu"
icities="beijing shanghai shenzhen guangzhou chengdu manila kuala-lumpur seoul osaka tokyo sydney melbourne brisbane newyork"

if [ $# -eq 0 ]
then
    aqi songpa-gu
    exit 0
fi

if [ $1 == "-c" ]
then
    aqi $cities
    exit 0
elif [ $1 == "-s" ]
then
    aqi $gus
elif [ $1 == "-i" ]
then
    aqi $icities
elif [ $1 == "-h" ]
then
    echo "option: -c shows all cities, -i shows all international cities, -s shows district in seoul"
fi

for city in "$@"
do
    fcity=$city
    if [[ $city =~ .*-gu$ ]]
    then
        fcity="korea/seoul/$city"
    fi 
    r=$(w3m -dump aqicn.org/city/$fcity/en | egrep -oE "overall air quality index is [0-9]+$")
    n=6
    ar=($r)
    aqi_index=${ar[n-1]}

    [ -z $aqi_index  ] && continue
    #printf "$token AQI is $aqi_index"
    
    if [ $aqi_index -le 30 ]
    then
        msg="매우 좋습니다"
        pre="\e[96m"
    elif [ $aqi_index -le 50 ]
    then
        msg="좋은 편입니다"
        pre="\e[32m"
    elif [ $aqi_index -le 100 ]
    then
        msg="보통입니다"
        pre="\e[93m"
    elif [ $aqi_index -le 150 ]
    then
        msg="민감한 사람에겐 해롭습니다"
        pre="\e[33m"
    elif [ $aqi_index -le 200 ]
    then
        msg="건강에 좋지 않습니다."
        pre="\e[91m"
    elif [ $aqi_index -le 300 ]
    then
        msg="매우 건강에 해롭습니다. "
        pre="\e[35m"
    else
        msg="끔찍한 재앙입니다."
        pre="\e[35m"
    fi

    app="\e[0m"

    printf "$city 의 대기오염지수는 $pre$aqi_index$app 입니다. $pre$msg$app\n"
done
