#!/bin/sh


sudo apt-get clean
sudo apt-get autoclean
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade
sudo apt-get autoremove
sudo apt-get autoclean
sudo apt-get clean
sudo apt-get check
