#!/bin/bash
# usage: coin [btc eth etc...]

contents=$(w3m -dump coinmarketcap.com)
total=100
regex='^([0-9]+) +'
regex+='([A-Z]+)+ +'
regex+='([^$]+) +'
regex+='(\$[0-9,]+) +'
regex+='(\$[0-9,.]+) +'
regex+='([0-9,.]+) +'
regex+='([A-Z]*) +'
regex+='(\$[0-9,.]+) +'
regex+='([-0-9,.]+%)'

i=0
while read -r line
do
    if [[ $line =~ $regex ]]; then
        rank="${BASH_REMATCH[1]}"
        coin="${BASH_REMATCH[2]}"
        name="${BASH_REMATCH[3]}"
        price="${BASH_REMATCH[5]}"
        vol="${BASH_REMATCH[8]}"
        change="${BASH_REMATCH[9]}"
        # Filter the results if parameters are given.
        if [ $# -gt 0 ]; then
            found=0
            for c in "$@"; do
                c=$(echo "$c" | tr [a-z] [A-Z])
                n=$(echo "$name" | tr [a-z] [A-Z])
                if [[ "$c" == "$coin" || "$n" =~ .*"$c".* ]]; then
                   found=1
                fi
            done
            if [ $found -eq 0 ]; then
                continue
            fi
        fi
        ranks[$i]=$rank
        coins[$i]=$coin
        names[$i]=$name
        prices[$i]=$price
        vols[$i]=$vol
        changes[$i]=$change
        i=$((i+1))
    fi
    if [ $i -eq $total ]; then
        break
    fi
done <<< "$(echo -e "$contents")"

# Print in a form
printf "%-3s | %-17s | %+10s | %+15s | %+7s\n" \
    "RNK" "COIN" "PRICE" "VOLUME(24h)" "CHNG(24h)"
echo "-----------------------------------------------------------------"
for (( i=0; i<${#ranks[@]}; i++ )); do
    printf "%-3s | %-17s | %+10s | %+15s | %+7s\n" \
        "${ranks[$i]}" "${names[$i]}" "${prices[$i]}" \
        "${vols[$i]}" "${changes[$i]}"
done
