#!/bin/bash
# usage: coin [btc eth etc...]

contents=$(w3m -dump coinmarketcap.com)
total=100
regex='^([0-9]+) +'   # 1.rank
regex+='([A-Z]+)+ +'  # 2.coin
regex+='([^$]+) +'    # 3.name
regex+='(\$[0-9,]+) +'  # 4. market cap
regex+='(\$[0-9,.]+) +'  # 5. price
regex+='(\$[0-9,]+) +' # 6. volume
regex+='([0-9,.]+) +' # 7.circulating supply
regex+='([A-Z]*) +'  # 8.optional unit
regex+='([-0-9,.]+%)'  # 9.change

i=0
while read -r line
do
    if [[ $line =~ $regex ]]; then
        rank="${BASH_REMATCH[1]}"
        coin="${BASH_REMATCH[2]}"
        name="${BASH_REMATCH[3]}"
        mcap="${BASH_REMATCH[4]}"
        price="${BASH_REMATCH[5]}"
        vol="${BASH_REMATCH[6]}"
        change="${BASH_REMATCH[9]}"
        # Filter the results if parameters are given.
        if [ $# -gt 0 ]; then
            found=0
            for c in "$@"; do
                c=$(echo "$c" | tr [a-z] [A-Z])
                n=$(echo "$name" | tr [a-z] [A-Z])
                if [[ "$c" == "$coin" || "$n" =~ .*"$c".* ]]; then
                   found=1
                fi
            done
            if [ $found -eq 0 ]; then
                continue
            fi
        fi
        ranks[$i]=$rank
        coins[$i]=$coin
        names[$i]=$name
        mcaps[$i]=$mcap
        prices[$i]=$price
        vols[$i]=$vol
        changes[$i]=$change
        if [ $coin == "BTC" ]; then
            btc_mcap=$mcap
        fi
        i=$((i+1))
    fi
    if [ $i -eq $total ]; then
        break
    fi
done <<< "$(echo -e "$contents")"

# Print in a form
printf "%-3s | %+20s | %+9s | %+13s | %+12s | %+7s\n" \
    "RNK" "NAME & SYMBOL" "PRICE" "Market Cap" "VOLUME(24h)" "CHNG(24h)"
echo "---------------------------------------------------------------------------------"
for (( i=0; i<${#ranks[@]}; i++ )); do
    # Truncate trailing spaces
    names[$i]=$(echo ${names[$i]} | sed 's/ $//')
    # Shorten prices 
    mcaps[$i]=$(echo ${mcaps[$i]} | sed 's/,[0-9]\+$/k/g') 
    vols[$i]=$(echo ${vols[$i]} | sed 's/,[0-9]\+$/k/g')
    printf "%-3s | %+20s | %+9s | %+13s | %+12s | %+7s\n" \
        "${ranks[$i]}" "${names[$i]} ${coins[$i]}" "${prices[$i]}" \
        "${mcaps[$i]}" "${vols[$i]}" "${changes[$i]}"
done

total_market_cap=$(echo -ne "$contents" | grep "Total Market Cap:" | awk -F$ '{print $2}')
total_market_cap=$(echo $total_market_cap | sed 's/,//g')
btc_mcap=$(echo -ne "$btc_mcap" | awk -F$ '{print $2}' | sed 's/,//g')
echo BTC%:$(bc <<< "scale = 4; $btc_mcap / $total_market_cap")
