#!/bin/bash
# usage: coin [btc eth etc...]

contents=$(w3m -dump coinmarketcap.com)
total=100

i=0
while read -r line
do
    if [[ $line =~ ^[0-9]+[[:space:]]+[A-Z] ]]; then
        coin=$(echo $line | cut -d ' ' -f 2)
        name=$(echo $line | awk -F'$' '{print $1}' |\
            cut -d ' ' -f 3-4) 
        # Filter the results if parameters are given.
        if [ $# -gt 0 ]; then
            found=0
            for c in "$@"; do
                c=$(echo "$c" | tr [a-z] [A-Z])
                n=$(echo "$name" | tr [a-z] [A-Z])
                if [[ "$c" == "$coin"  || "$n" =~ .*"$c".* ]]; then
                   found=1
                fi
            done
            if [ $found -eq 0 ]; then
                continue
            fi
        fi
        lines[$i]=$line
        ranks[$i]=$(echo $line | cut -d ' ' -f 1)
        coins[$i]=$coin
        names[$i]=$name
        prices[$i]=$(echo $line | awk -F'$' '{print "$" $3}' |\
            cut -d ' ' -f 1)
        vols[$i]=$(echo $line | awk -F'$' '{print "$" $4}' |\
            cut -d ' ' -f 1)
        changes[$i]=$(echo $line | awk -F'$' '{print $4}' |\
           cut -d ' ' -f 2)
        let i=i+1
    fi
    if [ $i -eq $total ]; then
        break
    fi
done <<< "$(echo -e "$contents")"

# Print in a form
printf "%-3s | %-17s | %+10s | %+15s | %+7s\n" \
    "RNK" "COIN" "PRICE" "VOLUME(24h)" "CHNG(24h)"
echo "-----------------------------------------------------------------"
i=0
for p in ${prices[@]}; do
    printf "%-3s | %-17s | %+10s | %+15s | %+7s\n" \
        "${ranks[$i]}" "${names[$i]}" "$p" "${vols[$i]}" "${changes[$i]}"
    i=$i+1
done
