#!/bin/bash
fs=`grep 'FontName' ~/.config/xfce4/terminal/terminalrc | grep -oE '[0-9]+'`
if [ $1 == "+" ]
then
    nfs=$((fs + 1))
elif [ $1 == "-" ]
then
    nfs=$((fs - 1))
else
    exit 0
fi
echo $nfs
regex='s/'$fs'/'$nfs'/'
sed -i "$regex" ~/.config/xfce4/terminal/terminalrc
